/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm;

/**
 *
 * @author ANSHIKA
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }
    int MyAccNum;
    public MainMenu(int AccountNum) {
        initComponents();
        MyAccNum=AccountNum;
        AccNumlbl.setText(""+MyAccNum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xyz = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        DEPOSITbtn = new javax.swing.JButton();
        WITHDRAWbtn = new javax.swing.JButton();
        FASTCASHbtn = new javax.swing.JButton();
        MINISTATEMENTbtn = new javax.swing.JButton();
        CHANGEPINbtn = new javax.swing.JButton();
        BALANCEbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LOGOUTbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AccNumlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        xyz.setBackground(new java.awt.Color(153, 153, 255));
        xyz.setForeground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BANIYA    BANK");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("SELECT YOUR TRANSACTION PLEASE");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 51, 0));
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(98, 98, 98)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        DEPOSITbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DEPOSITbtn.setText("DEPOSIT");
        DEPOSITbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DEPOSITbtnMouseClicked(evt);
            }
        });

        WITHDRAWbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        WITHDRAWbtn.setText("WITHDRAW");
        WITHDRAWbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WITHDRAWbtnMouseClicked(evt);
            }
        });
        WITHDRAWbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WITHDRAWbtnActionPerformed(evt);
            }
        });

        FASTCASHbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FASTCASHbtn.setText("FAST CASH");
        FASTCASHbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FASTCASHbtnMouseClicked(evt);
            }
        });
        FASTCASHbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FASTCASHbtnActionPerformed(evt);
            }
        });

        MINISTATEMENTbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MINISTATEMENTbtn.setText("MINI STATEMENT");
        MINISTATEMENTbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MINISTATEMENTbtnMouseClicked(evt);
            }
        });
        MINISTATEMENTbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINISTATEMENTbtnActionPerformed(evt);
            }
        });

        CHANGEPINbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CHANGEPINbtn.setText("CHANGE PIN");
        CHANGEPINbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CHANGEPINbtnMouseClicked(evt);
            }
        });
        CHANGEPINbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHANGEPINbtnActionPerformed(evt);
            }
        });

        BALANCEbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BALANCEbtn.setText("BALANCE");
        BALANCEbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BALANCEbtnMouseClicked(evt);
            }
        });
        BALANCEbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BALANCEbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ACCOUNT NUMBER:");

        LOGOUTbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LOGOUTbtn.setText("LOGOUT");
        LOGOUTbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUTbtnMouseClicked(evt);
            }
        });
        LOGOUTbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTbtnActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("BANIYA BANK");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        AccNumlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AccNumlbl.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout xyzLayout = new javax.swing.GroupLayout(xyz);
        xyz.setLayout(xyzLayout);
        xyzLayout.setHorizontalGroup(
            xyzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xyzLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(xyzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xyzLayout.createSequentialGroup()
                        .addGroup(xyzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(xyzLayout.createSequentialGroup()
                                .addComponent(CHANGEPINbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BALANCEbtn)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, xyzLayout.createSequentialGroup()
                                .addComponent(FASTCASHbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                                .addComponent(MINISTATEMENTbtn)))
                        .addGap(78, 78, 78))
                    .addGroup(xyzLayout.createSequentialGroup()
                        .addComponent(DEPOSITbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WITHDRAWbtn)
                        .addGap(99, 99, 99))))
            .addGroup(xyzLayout.createSequentialGroup()
                .addGroup(xyzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xyzLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccNumlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(xyzLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(LOGOUTbtn)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xyzLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        xyzLayout.setVerticalGroup(
            xyzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xyzLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(xyzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xyzLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(xyzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(xyzLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(AccNumlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(xyzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WITHDRAWbtn)
                    .addComponent(DEPOSITbtn))
                .addGap(30, 30, 30)
                .addGroup(xyzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MINISTATEMENTbtn)
                    .addComponent(FASTCASHbtn))
                .addGap(27, 27, 27)
                .addGroup(xyzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BALANCEbtn)
                    .addComponent(CHANGEPINbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(LOGOUTbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xyz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xyz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGOUTbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUTbtnActionPerformed

    private void BALANCEbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BALANCEbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BALANCEbtnActionPerformed

    private void CHANGEPINbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHANGEPINbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHANGEPINbtnActionPerformed

    private void MINISTATEMENTbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINISTATEMENTbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MINISTATEMENTbtnActionPerformed

    private void FASTCASHbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FASTCASHbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FASTCASHbtnActionPerformed

    private void WITHDRAWbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WITHDRAWbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WITHDRAWbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DEPOSITbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DEPOSITbtnMouseClicked
        new Deposit(MyAccNum).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DEPOSITbtnMouseClicked

    private void WITHDRAWbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WITHDRAWbtnMouseClicked
         new Withdraws(MyAccNum).setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_WITHDRAWbtnMouseClicked

    private void BALANCEbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BALANCEbtnMouseClicked
           new Balances(MyAccNum).setVisible(true);// TODO add your handling code here:
           this.dispose();
    }//GEN-LAST:event_BALANCEbtnMouseClicked

    private void CHANGEPINbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHANGEPINbtnMouseClicked
         new ChangePIN(MyAccNum).setVisible(true);// TODO add your handling code here:
           this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CHANGEPINbtnMouseClicked

    private void FASTCASHbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FASTCASHbtnMouseClicked
        new FastCash(MyAccNum).setVisible(true);
     this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_FASTCASHbtnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
System.exit(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void LOGOUTbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTbtnMouseClicked
    new LOGIN().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUTbtnMouseClicked

    private void MINISTATEMENTbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINISTATEMENTbtnMouseClicked
   new MiniStatements().setVisible(true);
   this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_MINISTATEMENTbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccNumlbl;
    private javax.swing.JButton BALANCEbtn;
    private javax.swing.JButton CHANGEPINbtn;
    private javax.swing.JButton DEPOSITbtn;
    private javax.swing.JButton FASTCASHbtn;
    private javax.swing.JButton LOGOUTbtn;
    private javax.swing.JButton MINISTATEMENTbtn;
    private javax.swing.JButton WITHDRAWbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel xyz;
    // End of variables declaration//GEN-END:variables
}
